In [1]:
import numpy as np

In [2]:
from numba import vectorize, float32, float64

In [3]:
@vectorize([float32(float32, float32), float64(float64, float64)])
def f(x, y):
    return x + y

In [4]:
a = np.random.rand(5)
a

array([0.93199185, 0.79430475, 0.46552297, 0.53830659, 0.41454096])

In [5]:
b = np.random.rand(5)
b

array([0.15642961, 0.77881834, 0.76113101, 0.75799226, 0.9130883 ])

In [6]:
f(a,b)

array([1.08842146, 1.57312309, 1.22665399, 1.29629884, 1.32762926])

In [7]:
c = np.random.rand(5).astype(np.float32)
c

array([0.954751  , 0.5709326 , 0.32670304, 0.5369359 , 0.8929944 ],
      dtype=float32)

In [8]:
d = np.random.rand(5).astype(np.float32)
d

array([0.609814  , 0.69907564, 0.9403815 , 0.84067124, 0.5056764 ],
      dtype=float32)

In [9]:
f(c,d)

array([1.564565 , 1.2700083, 1.2670846, 1.3776071, 1.3986708],
      dtype=float32)